// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DetectFunction
 */
export interface DetectFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/slack-textract/detect.
 */
export class DetectFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DetectFunctionProps) {
    super(scope, id, {
      description: 'src/slack-textract/detect.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/slack-textract/detect.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}