// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for OriginRequestFunction
 */
export interface OriginRequestFunctionProps extends cloudfront.experimental.EdgeFunctionProps {
}

/**
 * An AWS Lambda function which executes src/static-website/origin-request.
 */
export class OriginRequestFunction extends cloudfront.experimental.EdgeFunction {
  constructor(scope: Construct, id: string, props?: OriginRequestFunctionProps) {
    super(scope, id, {
      description: 'src/static-website/origin-request.edge-lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/static-website/origin-request.edge-lambda')),
    });
  }
}