// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RedirectFunction
 */
export interface RedirectFunctionProps extends cloudfront.experimental.EdgeFunctionProps {
}

/**
 * An AWS Lambda function which executes src/url-shortener/redirect.
 */
export class RedirectFunction extends cloudfront.experimental.EdgeFunction {
  constructor(scope: Construct, id: string, props?: RedirectFunctionProps) {
    super(scope, id, {
      description: 'src/url-shortener/redirect.edge-lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/url-shortener/redirect.edge-lambda')),
    });
  }
}