// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for CleanFunction
 */
export interface CleanFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/toolkit-cleaner/clean.
 */
export class CleanFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CleanFunctionProps) {
    super(scope, id, {
      description: 'src/toolkit-cleaner/clean.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/toolkit-cleaner/clean.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}