// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ExtractTemplateHashesFunction
 */
export interface ExtractTemplateHashesFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/toolkit-cleaner/extract-template-hashes.
 */
export class ExtractTemplateHashesFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ExtractTemplateHashesFunctionProps) {
    super(scope, id, {
      description: 'src/toolkit-cleaner/extract-template-hashes.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/toolkit-cleaner/extract-template-hashes.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}